# Generated by Django 3.2.5 on 2024-02-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Напишите хегтег')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('description', models.TextField(blank=True, verbose_name='Описание продукта')),
                ('price', models.PositiveIntegerField(verbose_name='Укажите цену продукта')),
                ('tags', models.ManyToManyField(to='product.HashTag')),
            ],
        ),
    ]
