# Generated by Django 3.2.5 on 2024-02-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20240212_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='#', max_length=100, verbose_name='Напишите тег')),
            ],
        ),
        migrations.CreateModel(
            name='ProductClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название одежды')),
                ('description', models.TextField(blank=True, verbose_name='Описание продукта')),
                ('price', models.PositiveIntegerField(verbose_name='Укажите цену одежды')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='product.Tag')),
            ],
        ),
    ]
