# Generated by Django 3.2.5 on 2024-02-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LalafoItems',
            new_name='MashinakgItems',
        ),
    ]
