# Generated by Django 3.2.5 on 2024-01-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Укажите название фильма')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Укажите описание')),
                ('image', models.URLField(verbose_name='Вставьте ссылку на фото')),
                ('sport', models.CharField(choices=[('Боевик', 'Боевик'), ('Драма', 'Драма'), ('Комедия', 'Комедия'), ('Романтика', 'Романтика'), ('Научная фантастика (Sci-Fi)', 'Научная фантастика (Sci-Fi)'), ('Фэнтези', 'Фэнтези'), ('Детектив', 'Детектив'), ('Триллер', 'Триллер'), ('Документальный', 'Документальный')], max_length=100, verbose_name='Выберите жанр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
