# Generated by Django 3.2.5 on 2024-01-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.PositiveIntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], default=5, verbose_name='Поставьте звезду'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Введите комментарий'),
        ),
    ]
