# Generated by Django 3.2.5 on 2024-02-05 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0005_review_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(choices=[('Боевик', 'Боевик'), ('Драма', 'Драма'), ('Комедия', 'Комедия'), ('Романтика', 'Романтика'), ('Научная фантастика (Sci-Fi)', 'Научная фантастика (Sci-Fi)'), ('Фэнтези', 'Фэнтези'), ('Детектив', 'Детектив'), ('Триллер', 'Триллер'), ('Документальный', 'Докуeментальный')], max_length=100, verbose_name='Выберите жанр'),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tv_show.movies'),
        ),
    ]
