# Generated by Django 3.2.5 on 2024-02-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('KGZ', 'Kyrgyzstan'), ('USA', 'United States'), ('CAN', 'Canada'), ('GBR', 'United Kingdom'), ('KZ', 'Kazakhstan'), ('UZB', 'Uzbekistan'), ('KR', 'South Korea'), ('RUS', 'Russia'), ('JP', 'Japam')], default='KGZ', max_length=50),
        ),
    ]
