# Generated by Django 3.2.5 on 2024-01-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekken_persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personsgame',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AddField(
            model_name='personsgame',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Укажите описание'),
        ),
        migrations.AlterField(
            model_name='personsgame',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Укажите имя персонажа'),
        ),
    ]
